context:
  name: laura
  version: "3.7.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: "https://laura.hepforge.org/downloads?f=Laura-${{ version }}.tar.gz"
  sha256: 4bb233590f411d6b5a3138d995955cc9d0075af95209d0e2131fa28fc10eab89

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - make
  host:
    - root
    - root_base
    - root_cxx_standard
  run:
    - ${{ pin_compatible('root_base', upper_bound='x.x') }}
  run_exports:
    - ${{ pin_subpackage('laura', upper_bound='x.x') }}

tests:
  - script:
      - cmake-package-check Laura --targets Laura::Laura++
    requirements:
      run:
        - cmake-package-check
        - if: linux
          then:
            - gcc_linux-64
            - gxx_linux-64
          else:
            - clang
            - clangxx

about:
  homepage: https://laura.hepforge.org/
  summary: 'A maximum likelihood fitter for Dalitz-plot analysis'
  description: |
    Laura++ is a maximum likelihood fitting package for performing Dalitz-plot
    analysis.  It is written in C++ and depends only on the ROOT
    <https://root.cern.ch> data analysis framework.
  license: Apache-2.0
  license_file: LICENSE-2.0
  documentation: https://laura.hepforge.org/doc/
  repository: https://repo.hepforge.org/source/laura/

extra:
  recipe-maintainers:
    - tomlatham
